---
- name: Post Kubernetes Installation - Pure Storage Orchestrator
  hosts: 127.0.0.1
  connection: local
  vars:
    - namespace: kube-system
    - kubectl: kubectl
    - helm: helm
  tasks:
    - name: helm init
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      local_action: command {{ helm }} init --client-only 
      ignore_errors: yes
  
    - name: helm add pure repo
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      local_action: command {{ helm }} repo add pure https://purestorage.github.io/helm-charts
      ignore_errors: yes

    - name: Update helm
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      local_action: command {{ helm }} repo update 
      ignore_errors: yes

    - name: Configure cluster admin
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      local_action: command {{ kubectl }} create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount={{ namespace }}:default
      ignore_errors: yes

    - name: Install Pure Service Orchestrator 
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      local_action: command {{ helm }} install --name pure-storage-orchestrator pure/pure-k8s-plugin -f {{ psoconfig }} --namespace {{ namespace }}
      ignore_errors: yes

    - name: Setup Default StorageClass Pure
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      local_action: command {{ kubectl }} patch storageclass pure-block -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}' 
      ignore_errors: yes  



